// <auto-generated />
using Day4InClass.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Day4InClass.Data.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20201201181643_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("Day4InClass.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bake Cookies",
                            IsComplete = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "Eat the cookies",
                            IsComplete = false
                        },
                        new
                        {
                            Id = 3,
                            Description = "Run around the block",
                            IsComplete = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
